# Generated by Django 5.0.2 on 2024-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='pena',
            field=models.CharField(default='', max_length=50),
        ),
    ]
